# Generated by Django 5.1.6 on 2025-03-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VectorProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                ("sku", models.CharField(blank=True, max_length=100, null=True)),
                ("thumbnail", models.URLField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Product",
                "db_table": "demo_products",
                "unique_together": {("title", "brand", "category")},
            },
        ),
    ]
